/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package GUI;

import DAO.ChiTietHoaDonNhapKhoDAO;
import DAO.HoaDonNhapKhoDAO;
import POJO.ChiTietHoaDonNhapKho;
import POJO.HoaDonNhapKho;
import POJO.NhanVien;
import POJO.NhanVienLogin;
import java.io.File;
import java.io.FileInputStream;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Date;
import java.util.Vector;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class frmNhapKho extends javax.swing.JInternalFrame {

    /**
     * Creates new form frmNhapKho
     */
    DefaultTableModel dtmHDNK = new DefaultTableModel();
    DefaultTableModel dtmCTHDNK = new DefaultTableModel();

    public frmNhapKho() {
        initComponents();
        String[] tieuDe = {"Mã hoá đơn nhập kho", "Mã nhân viên", "Tên Nhân viên", "Tổng tiền", "Ngày nhập"};
        dtmHDNK.setColumnIdentifiers(tieuDe);
        ResetMaNV();
        loadtblHoaDonNhapKho();
        String[] tieuDe1 = {"Mã hoá đơn nhập kho", "Kiểu sản phẩm", "Tên sản phẩm", "Số lượng", "Đơn giá"};
        dtmCTHDNK.setColumnIdentifiers(tieuDe1);
        loadtblChiTietHoaDonNhapKho();
    }

    private void loadtblHoaDonNhapKho() {

        ArrayList<HoaDonNhapKho> dsHDNK = HoaDonNhapKhoDAO.getAll();
        setHoaDonNhapKhoModel(dsHDNK);

    }

    private void loadtblChiTietHoaDonNhapKho() {
        ArrayList<ChiTietHoaDonNhapKho> dsCTHDNK = ChiTietHoaDonNhapKhoDAO.getAll();
        setCTHoaDonNhapKhoModel(dsCTHDNK);
    }

    private void setCTHoaDonNhapKhoModel(ArrayList<ChiTietHoaDonNhapKho> dsCTHDNK) {
        dtmCTHDNK.setRowCount(0);
        for (ChiTietHoaDonNhapKho hd : dsCTHDNK) {
            Vector<Object> vec = new Vector<>();
            vec.add(hd.getIdHoaDonNhapKho());
            vec.add(hd.getIdKieuSanPham());
            vec.add(hd.getSp());
            vec.add(hd.getSoLuong());
            vec.add(hd.getDonGia());

            dtmCTHDNK.addRow(vec);
        }
        tbl_ChiTietHoaDonNhapKho.setModel(dtmCTHDNK);
    }

    private void setHoaDonNhapKhoModel(ArrayList<HoaDonNhapKho> dsHDNK) {
        dtmHDNK.setRowCount(0);
        for (HoaDonNhapKho hd : dsHDNK) {
            Vector<Object> vec = new Vector<>();
            vec.add(hd.getIdHoaDonNhapKho());
            vec.add(hd.getIdNhanVien());
            vec.add(hd.getNhanvien());
            vec.add(hd.getTongTien());
            vec.add(hd.getNgayNhap());

            dtmHDNK.addRow(vec);
        }
        tbl_HoaDonNhapKho.setModel(dtmHDNK);
    }

    private void ResetMaNV() {
        NhanVien loggedInNV = NhanVienLogin.getNhanVienLogin().nhanVien;
        if (loggedInNV != null) {
            txtmaNV.setText(String.valueOf(loggedInNV.getIdNhanVien()));
        } else {
            txtmaNV.setText("");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtmaNV = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtmaHoaDon = new javax.swing.JTextField();
        btnLapHoaDonNhapKho = new javax.swing.JButton();
        btnXoaHoaDonNhapKho = new javax.swing.JButton();
        btnResetHoaDon = new javax.swing.JButton();
        btnUpdateHDNhapKho = new javax.swing.JButton();
        txttongTien = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txttenNV = new javax.swing.JTextField();
        dateChooseNgayNhap = new com.toedter.calendar.JDateChooser();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_HoaDonNhapKho = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtmahdnk = new javax.swing.JTextField();
        txtmaKieuSP = new javax.swing.JTextField();
        btnThemChiTietNhapKho = new javax.swing.JButton();
        btnXoaChiTietHDNhapKho = new javax.swing.JButton();
        btnUpdateChiTietNhapKho = new javax.swing.JButton();
        btnResetChiTietNhapKho = new javax.swing.JButton();
        txtdonGia = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtsoluong = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbl_ChiTietHoaDonNhapKho = new javax.swing.JTable();

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(187, 54, 137));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("QUẢN LÝ NHẬP KHO");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Thông tin hoá đơn nhập kho", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 14))); // NOI18N

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(187, 54, 137));
        jLabel7.setText("Ngày nhập");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(187, 54, 137));
        jLabel4.setText("Mã nhân viên");

        txtmaNV.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtmaNV.setEnabled(false);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(187, 54, 137));
        jLabel2.setText("Mã hoá đơn");

        txtmaHoaDon.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtmaHoaDon.setEnabled(false);

        btnLapHoaDonNhapKho.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnLapHoaDonNhapKho.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/add.png"))); // NOI18N
        btnLapHoaDonNhapKho.setText("Thêm");
        btnLapHoaDonNhapKho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLapHoaDonNhapKhoActionPerformed(evt);
            }
        });

        btnXoaHoaDonNhapKho.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnXoaHoaDonNhapKho.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/delete.png"))); // NOI18N
        btnXoaHoaDonNhapKho.setText("Xoá");
        btnXoaHoaDonNhapKho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaHoaDonNhapKhoActionPerformed(evt);
            }
        });

        btnResetHoaDon.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnResetHoaDon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/reset.png"))); // NOI18N
        btnResetHoaDon.setText("Reset");
        btnResetHoaDon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetHoaDonActionPerformed(evt);
            }
        });

        btnUpdateHDNhapKho.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnUpdateHDNhapKho.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/updated.png"))); // NOI18N
        btnUpdateHDNhapKho.setText("Cập nhật");
        btnUpdateHDNhapKho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateHDNhapKhoActionPerformed(evt);
            }
        });

        txttongTien.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txttongTien.setEnabled(false);

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(187, 54, 137));
        jLabel8.setText("Tổng tiền");

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(187, 54, 137));
        jLabel10.setText("Tên nhân viên");

        txttenNV.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txttenNV.setEnabled(false);

        dateChooseNgayNhap.setDateFormatString("yyyy-MM-dd");
        dateChooseNgayNhap.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(jLabel7)
                        .addGap(26, 26, 26))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txtmaHoaDon, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(txtmaNV, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(dateChooseNgayNhap, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel8)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txttongTien, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnResetHoaDon)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnXoaHoaDonNhapKho))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(0, 6, Short.MAX_VALUE)
                                .addComponent(btnLapHoaDonNhapKho)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnUpdateHDNhapKho))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addGap(18, 18, 18)
                        .addComponent(txttenNV, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txttenNV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnUpdateHDNhapKho)
                            .addComponent(btnLapHoaDonNhapKho)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addComponent(txttongTien)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnResetHoaDon)
                    .addComponent(btnXoaHoaDonNhapKho))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(jLabel4)
                        .addComponent(txtmaNV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtmaHoaDon, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel8)
                        .addComponent(jLabel7))
                    .addComponent(dateChooseNgayNhap, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Danh sách hoá đơn nhập kho", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 14))); // NOI18N

        tbl_HoaDonNhapKho.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbl_HoaDonNhapKho.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_HoaDonNhapKhoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_HoaDonNhapKho);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 672, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 376, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Thông tin chi tiết hoá đơn nhập kho", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 14))); // NOI18N

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(187, 54, 137));
        jLabel3.setText("Mã kiểu sản phẩm");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(187, 54, 137));
        jLabel5.setText("Mã hoá đơn nhập kho");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(187, 54, 137));
        jLabel6.setText("Số lượng");

        txtmahdnk.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtmahdnk.setEnabled(false);

        txtmaKieuSP.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtmaKieuSP.setEnabled(false);

        btnThemChiTietNhapKho.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnThemChiTietNhapKho.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/add.png"))); // NOI18N
        btnThemChiTietNhapKho.setText("Nhập hàng");
        btnThemChiTietNhapKho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemChiTietNhapKhoActionPerformed(evt);
            }
        });

        btnXoaChiTietHDNhapKho.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnXoaChiTietHDNhapKho.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/delete.png"))); // NOI18N
        btnXoaChiTietHDNhapKho.setText("Xoá");
        btnXoaChiTietHDNhapKho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaChiTietHDNhapKhoActionPerformed(evt);
            }
        });

        btnUpdateChiTietNhapKho.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnUpdateChiTietNhapKho.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/updated.png"))); // NOI18N
        btnUpdateChiTietNhapKho.setText("Cập nhật");
        btnUpdateChiTietNhapKho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateChiTietNhapKhoActionPerformed(evt);
            }
        });

        btnResetChiTietNhapKho.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnResetChiTietNhapKho.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/reset.png"))); // NOI18N
        btnResetChiTietNhapKho.setText("Reset");
        btnResetChiTietNhapKho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetChiTietNhapKhoActionPerformed(evt);
            }
        });

        txtdonGia.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(187, 54, 137));
        jLabel9.setText("Đơn giá");

        txtsoluong.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel3))
                        .addGap(13, 13, 13)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtmahdnk)
                            .addComponent(txtmaKieuSP, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(26, 26, 26)
                        .addComponent(txtdonGia, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addComponent(jLabel6)))
                .addGap(32, 32, 32)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btnXoaChiTietHDNhapKho)
                        .addGap(45, 45, 45)
                        .addComponent(btnResetChiTietNhapKho))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btnThemChiTietNhapKho)
                        .addGap(37, 37, 37)
                        .addComponent(btnUpdateChiTietNhapKho))
                    .addComponent(txtsoluong, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(17, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtmahdnk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnThemChiTietNhapKho)
                    .addComponent(btnUpdateChiTietNhapKho))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtmaKieuSP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnXoaChiTietHDNhapKho)
                    .addComponent(btnResetChiTietNhapKho))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtdonGia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(txtsoluong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Danh sách chi tiết hoá đơn nhập kho", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 14))); // NOI18N
        jPanel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        tbl_ChiTietHoaDonNhapKho.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbl_ChiTietHoaDonNhapKho.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_ChiTietHoaDonNhapKhoMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tbl_ChiTietHoaDonNhapKho);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(17, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 649, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 360, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 697, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(581, 581, 581)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 378, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(29, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(112, 112, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(14, 14, 14))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnThemChiTietNhapKhoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemChiTietNhapKhoActionPerformed
        JFileChooser fileChooser = new JFileChooser();
        int returnValue = fileChooser.showOpenDialog(null);
        if (returnValue == JFileChooser.APPROVE_OPTION) {
            File selectedFile = fileChooser.getSelectedFile();
            try (FileInputStream fis = new FileInputStream(selectedFile)) {
                importFromExcel(fis);
                JOptionPane.showMessageDialog(this, "Import thành công!", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
            } catch (IOException e) {
                JOptionPane.showMessageDialog(this, "Lỗi khi đọc file: " + e.getMessage(), "Lỗi", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_btnThemChiTietNhapKhoActionPerformed
    public void importFromExcel(FileInputStream fis) {
//        try {
//            Workbook workbook = WorkbookFactory.create(fis);
//            Sheet sheet = workbook.getSheetAt(0);
//
//            for (Row row : sheet) {
//                // Bỏ qua dòng tiêu đề (nếu có)
//                if (row.getRowNum() == 0) {
//                    continue;
//                }
//
//                long idHoaDonNhapKho = (long) row.getCell(0).getNumericCellValue();
//                long idKieuSanPham = (long) row.getCell(1).getNumericCellValue();
//                int soLuong = (int) row.getCell(2).getNumericCellValue();
//                long donGia = (long) row.getCell(3).getNumericCellValue();
//                ChiTietHoaDonNhapKho cthdnk = new ChiTietHoaDonNhapKho();
//                cthdnk.setIdHoaDonNhapKho(idHoaDonNhapKho);
//                cthdnk.setIdKieuSanPham(idKieuSanPham);
//                cthdnk.setSoLuong(soLuong);
//                cthdnk.setDonGia(donGia);
//                boolean success = ChiTietHoaDonNhapKhoDAO.insert(cthdnk);
//
//            }
//
//            workbook.close();
//        } catch (IOException e) {
//            e.printStackTrace();
//        }
    }
    private void btnLapHoaDonNhapKhoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLapHoaDonNhapKhoActionPerformed
        txtmaHoaDon.setText("");
        txttongTien.setText("");
        ResetMaNV();
        int maNV = Integer.parseInt(txtmaNV.getText());
        HoaDonNhapKho hdnk = new HoaDonNhapKho();
        hdnk.setIdNhanVien(maNV);
        boolean result = HoaDonNhapKhoDAO.add(hdnk);
        if (result) {
            JOptionPane.showMessageDialog(this, "Thêm hoá đơn nhập kho thành công", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
            loadtblHoaDonNhapKho();
        } else {
            JOptionPane.showMessageDialog(this, "Thêm hoá đơn nhập kho thất bại", "Thông báo", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnLapHoaDonNhapKhoActionPerformed

    private void btnXoaHoaDonNhapKhoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaHoaDonNhapKhoActionPerformed
        long mahdnk = Long.parseLong(txtmaHoaDon.getText());
        NhanVien loggedInNV = NhanVienLogin.getNhanVienLogin().nhanVien;
        long check = loggedInNV.getIdNhanVien();
        long maNV = Long.parseLong(txtmaNV.getText());
        String role = loggedInNV.getVaitro() + "";
        if (maNV == check || role.equals("Admin") || role.equals("Quản lý")) {
            if (txtmaHoaDon.getText().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Vui lòng chọn hoá đơn muốn xoá ở danh sách dưới");
            } else {
                if (HoaDonNhapKhoDAO.isForeignKeyExistsCTHDNhapKho(mahdnk)) {
                    JOptionPane.showMessageDialog(this, "Mã hoá đơn đang được sử dụng và không thể xóa!", "Lỗi", JOptionPane.ERROR_MESSAGE);
                } else {
                    boolean success = HoaDonNhapKhoDAO.deleteById(mahdnk);
                    if (success) {
                        JOptionPane.showMessageDialog(this, "Xóa thành công!", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
                        ResetTTHDNhapKho();
                        loadtblHoaDonNhapKho();
                    } else {
                        JOptionPane.showMessageDialog(this, "Xóa không thành công!", "Thông báo", JOptionPane.ERROR_MESSAGE);
                    }
                }
            }
        } else {
            JOptionPane.showMessageDialog(this, "Bạn không được phép xóa!", "Cảnh báo", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btnXoaHoaDonNhapKhoActionPerformed
    public void ResetTTHDNhapKho() {
        txtmaHoaDon.setText("");
        dateChooseNgayNhap.setDate(null);
        txttongTien.setText("");
        ResetMaNV();
    }

    public void ResetTT_ChiTietHDNhapKho() {
        txtmahdnk.setText("");
        txtmaKieuSP.setText("");
        txtdonGia.setText("");
        txtsoluong.setText("");
        loadtblChiTietHoaDonNhapKho();
    }
    private void btnResetHoaDonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetHoaDonActionPerformed
        ResetTTHDNhapKho();
    }//GEN-LAST:event_btnResetHoaDonActionPerformed

    private void btnUpdateHDNhapKhoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateHDNhapKhoActionPerformed
        long mahdnk = Long.parseLong(txtmaHoaDon.getText());
        NhanVien loggedInNV = NhanVienLogin.getNhanVienLogin().nhanVien;
        long check = loggedInNV.getIdNhanVien();
        int maNV = Integer.parseInt(txtmaNV.getText());
        String Role = loggedInNV.getVaitro() + "";

        if (maNV == check || Role.equals("Admin") || Role.equals("Quản lý")) {
            if (txtmaHoaDon.getText().trim().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Vui lòng chọn hoá đơn muốn cập nhật ở danh sách dưới");
            } else {
                HoaDonNhapKho hdnk = new HoaDonNhapKho();
                hdnk.setIdHoaDonNhapKho(mahdnk);
                hdnk.setIdNhanVien(maNV);
                Date ngayNhap = dateChooseNgayNhap.getDate();
                hdnk.setNgayNhap(ngayNhap);
                boolean success = HoaDonNhapKhoDAO.updateById(hdnk);
                if (success) {
                    JOptionPane.showMessageDialog(this, "Cập nhật thành công!", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
                    ResetTTHDNhapKho();
                    loadtblHoaDonNhapKho();
                } else {
                    JOptionPane.showMessageDialog(this, "Cập nhật không thành công!", "Thông báo", JOptionPane.ERROR_MESSAGE);
                }
            }
        } else {
            JOptionPane.showMessageDialog(this, "Bạn không được phép cập nhật!", "Cảnh báo", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btnUpdateHDNhapKhoActionPerformed

    private void tbl_HoaDonNhapKhoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_HoaDonNhapKhoMouseClicked
        int row = tbl_HoaDonNhapKho.getSelectedRow();
        txtmaHoaDon.setText(tbl_HoaDonNhapKho.getValueAt(row, 0) + "");
        txtmaNV.setText(tbl_HoaDonNhapKho.getValueAt(row, 1) + "");
        txttenNV.setText(tbl_HoaDonNhapKho.getValueAt(row, 2) + "");
        txttongTien.setText(tbl_HoaDonNhapKho.getValueAt(row, 3) + "");
        dateChooseNgayNhap.setDate((Date) tbl_HoaDonNhapKho.getValueAt(row, 4));
    }//GEN-LAST:event_tbl_HoaDonNhapKhoMouseClicked

    private void btnXoaChiTietHDNhapKhoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaChiTietHDNhapKhoActionPerformed
        long mahdnk = Long.parseLong(txtmahdnk.getText());
        NhanVien loggedInNV = NhanVienLogin.getNhanVienLogin().nhanVien;
        long check = loggedInNV.getIdNhanVien();
        long maNV = Long.parseLong(txtmaNV.getText());
        long maSP = Long.parseLong(txtmaKieuSP.getText());
        String role = loggedInNV.getVaitro() + "";
        if (maNV == check || role.equals("Admin") || role.equals("Quản lý")) {
            if (mahdnk == 0) {
                JOptionPane.showMessageDialog(this, "Vui lòng chọn hoá đơn muốn xoá ở danh sách dưới");
            } else {
                boolean success = ChiTietHoaDonNhapKhoDAO.deleteById(mahdnk, maSP);
                if (success) {
                    JOptionPane.showMessageDialog(this, "Xóa thành công!", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
                    ResetTT_ChiTietHDNhapKho();
                    loadtblChiTietHoaDonNhapKho();
                    loadtblHoaDonNhapKho();
                } else {
                    JOptionPane.showMessageDialog(this, "Xóa không thành công!", "Thông báo", JOptionPane.ERROR_MESSAGE);
                }
            }
        } else {
            JOptionPane.showMessageDialog(this, "Bạn không được phép xóa!", "Cảnh báo", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btnXoaChiTietHDNhapKhoActionPerformed

    private void btnUpdateChiTietNhapKhoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateChiTietNhapKhoActionPerformed
        long mahdnk = Long.parseLong(txtmahdnk.getText());
        NhanVien loggedInNV = NhanVienLogin.getNhanVienLogin().nhanVien;
        long check = loggedInNV.getIdNhanVien();
        int maNV = Integer.parseInt(txtmaNV.getText());
        String Role = loggedInNV.getVaitro() + "";
        int sl = Integer.parseInt(txtsoluong.getText());
        long donGia = Long.parseLong(txtdonGia.getText());
        long maSP = Long.parseLong(txtmaKieuSP.getText());

        if (maNV == check || Role.equals("Admin") || Role.equals("Quản lý")) {
            if (txtmahdnk.getText().trim().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Vui lòng chọn hoá đơn muốn cập nhật ở danh sách dưới");
            } else {
                ChiTietHoaDonNhapKho cthdnk = new ChiTietHoaDonNhapKho();
                cthdnk.setIdHoaDonNhapKho(mahdnk);
                cthdnk.setIdKieuSanPham(maSP);
                cthdnk.setSoLuong(sl);
                cthdnk.setDonGia(donGia);
                boolean success = ChiTietHoaDonNhapKhoDAO.updateById(cthdnk);
                if (success) {
                    JOptionPane.showMessageDialog(this, "Cập nhật thành công!", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
                    ResetTT_ChiTietHDNhapKho();
                    loadtblHoaDonNhapKho();
                    loadtblChiTietHoaDonNhapKho();
                } else {
                    JOptionPane.showMessageDialog(this, "Cập nhật không thành công!", "Thông báo", JOptionPane.ERROR_MESSAGE);
                }
            }
        } else {
            JOptionPane.showMessageDialog(this, "Bạn không được phép cập nhật!", "Cảnh báo", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btnUpdateChiTietNhapKhoActionPerformed

    private void tbl_ChiTietHoaDonNhapKhoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_ChiTietHoaDonNhapKhoMouseClicked
        int row = tbl_ChiTietHoaDonNhapKho.getSelectedRow();
        txtmahdnk.setText(tbl_ChiTietHoaDonNhapKho.getValueAt(row, 0) + "");
        txtmaKieuSP.setText(tbl_ChiTietHoaDonNhapKho.getValueAt(row, 1) + "");
        txtsoluong.setText(tbl_ChiTietHoaDonNhapKho.getValueAt(row, 3) + "");
        txtdonGia.setText(tbl_ChiTietHoaDonNhapKho.getValueAt(row, 4) + "");

    }//GEN-LAST:event_tbl_ChiTietHoaDonNhapKhoMouseClicked

    private void btnResetChiTietNhapKhoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetChiTietNhapKhoActionPerformed
        loadtblChiTietHoaDonNhapKho();
    }//GEN-LAST:event_btnResetChiTietNhapKhoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLapHoaDonNhapKho;
    private javax.swing.JButton btnResetChiTietNhapKho;
    private javax.swing.JButton btnResetHoaDon;
    private javax.swing.JButton btnThemChiTietNhapKho;
    private javax.swing.JButton btnUpdateChiTietNhapKho;
    private javax.swing.JButton btnUpdateHDNhapKho;
    private javax.swing.JButton btnXoaChiTietHDNhapKho;
    private javax.swing.JButton btnXoaHoaDonNhapKho;
    private com.toedter.calendar.JDateChooser dateChooseNgayNhap;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tbl_ChiTietHoaDonNhapKho;
    private javax.swing.JTable tbl_HoaDonNhapKho;
    private javax.swing.JTextField txtdonGia;
    private javax.swing.JTextField txtmaHoaDon;
    private javax.swing.JTextField txtmaKieuSP;
    private javax.swing.JTextField txtmaNV;
    private javax.swing.JTextField txtmahdnk;
    private javax.swing.JTextField txtsoluong;
    private javax.swing.JTextField txttenNV;
    private javax.swing.JTextField txttongTien;
    // End of variables declaration//GEN-END:variables
}
