/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package GUI;

import DAO.NhanVienDAO;
import DAO.VaiTroDAO;
import POJO.NhanVien;
import POJO.VaiTro;
import Utils.PasswordHashing;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class frmQLNhanVien extends javax.swing.JInternalFrame {

    DefaultTableModel dtmNV = new DefaultTableModel();

//    ArrayList<NhanVien> lstDeleteNV = new ArrayList<>();
//    ArrayList<NhanVien> lstUpdateNV = new ArrayList<>();
    public frmQLNhanVien() {
        initComponents();
        String[] tieuDe = {"Mã nhân viên", "Tên tài khoản", "Mật khẩu", "Tên vai trò", "Tên nhân viên", "Ngày sinh", "Giới tính", "Địa chỉ", "Số điện thoại", "Email", "Tồn tại", "Cấm"};
        dtmNV.setColumnIdentifiers(tieuDe);

        loadtblNhanVien();
        LoadCboVaiTro();
    }

    private void setNhanVienModel(ArrayList<NhanVien> dsNV) {
        dtmNV.setRowCount(0);
        for (NhanVien nv : dsNV) {
            Vector<Object> vec = new Vector<>();
            vec.add(nv.getIdNhanVien());
            vec.add(nv.getTenTaiKhoan());
            vec.add(nv.getMatKhau());
            vec.add(nv.getVaitro());
            vec.add(nv.getTenNhanVien());
            vec.add(nv.getNgaySinh());
            vec.add(nv.getGioiTinh());
            vec.add(nv.getDiaChi());
            vec.add(nv.getSoDienThoai());
            vec.add(nv.getEmail());
            vec.add(nv.isTonTai());
            vec.add(nv.isCam());

            dtmNV.addRow(vec);

        }
        tblNhanVien.setModel(dtmNV);
    }

    private void loadtblNhanVien() {

        ArrayList<NhanVien> dsNV = NhanVienDAO.getAll();
        setNhanVienModel(dsNV);

    }

    private void LoadCboVaiTro() {
        cboVaiTro.removeAllItems();
        ArrayList<VaiTro> dsVaiTros = VaiTroDAO.getAll();
        for (VaiTro vaitro : dsVaiTros) {
            cboVaiTro.addItem(vaitro);
        }
    }

    private void resetFieldsTTNV() {
        txtmaNV.setText("");
        txttenNhanVien.setText("");
        buttonGroup1.clearSelection();
        txtngaysinh.setText("");
        cboVaiTro.setSelectedIndex(-1);
        txtDiaChi.setText("");
        txtsdt.setText("");
        txtEmail.setText("");
        txttenTK.setText("");
        txtpassword.setText("");
        chkTonTai.setSelected(false);
        chkCam.setSelected(false);
        loadtblNhanVien();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        txtmaNV = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txttenNhanVien = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        txtsdt = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        btnAdd = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnReset = new javax.swing.JButton();
        txtngaysinh = new javax.swing.JFormattedTextField();
        chkCam = new javax.swing.JCheckBox();
        jLabel6 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txttenTK = new javax.swing.JTextField();
        cboVaiTro = new javax.swing.JComboBox<>();
        jLabel13 = new javax.swing.JLabel();
        chkTonTai = new javax.swing.JCheckBox();
        txtpassword = new javax.swing.JPasswordField();
        rbNam = new javax.swing.JRadioButton();
        rbNu = new javax.swing.JRadioButton();
        jLabel14 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtDiaChi = new javax.swing.JTextArea();
        jLabel19 = new javax.swing.JLabel();
        txtFind = new javax.swing.JTextField();
        btnFind = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        dateNgayKT = new com.toedter.calendar.JDateChooser();
        dateNgayBD = new com.toedter.calendar.JDateChooser();
        jButton1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblNhanVien = new javax.swing.JTable();

        setMaximumSize(new java.awt.Dimension(1536, 778));
        setMinimumSize(new java.awt.Dimension(1536, 778));
        setPreferredSize(new java.awt.Dimension(1536, 778));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(187, 54, 137));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("DANH SÁCH NHÂN VIÊN");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(592, 26, 378, -1));

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Thông tin nhân viên", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 14))); // NOI18N
        jPanel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jPanel1.setMaximumSize(new java.awt.Dimension(450, 700));
        jPanel1.setMinimumSize(new java.awt.Dimension(450, 700));
        jPanel1.setPreferredSize(new java.awt.Dimension(450, 700));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(187, 54, 137));
        jLabel5.setText("Mã nhân viên");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, -1));

        txtmaNV.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtmaNV.setEnabled(false);
        jPanel1.add(txtmaNV, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 30, 78, -1));

        jLabel16.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(187, 54, 137));
        jLabel16.setText("Số điện thoại");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, -1, -1));

        txtEmail.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jPanel1.add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 210, 179, -1));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(187, 54, 137));
        jLabel11.setText("Tên nhân viên");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, -1, -1));

        txttenNhanVien.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jPanel1.add(txttenNhanVien, new org.netbeans.lib.awtextra.AbsoluteConstraints(116, 65, 198, -1));

        jLabel15.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(187, 54, 137));
        jLabel15.setText("Giới tính");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, -1, -1));

        jLabel17.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(187, 54, 137));
        jLabel17.setText("Email");
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, -1, -1));

        txtsdt.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jPanel1.add(txtsdt, new org.netbeans.lib.awtextra.AbsoluteConstraints(136, 179, 178, -1));

        jLabel18.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(187, 54, 137));
        jLabel18.setText("Ngày sinh");
        jPanel1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, -1, -1));

        btnAdd.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnAdd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/add.png"))); // NOI18N
        btnAdd.setText("Thêm");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });
        jPanel1.add(btnAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(332, 77, -1, -1));

        btnDelete.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/delete.png"))); // NOI18N
        btnDelete.setText("Xoá");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        jPanel1.add(btnDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(342, 129, -1, -1));

        btnUpdate.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnUpdate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/updated.png"))); // NOI18N
        btnUpdate.setText("Cập nhật");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });
        jPanel1.add(btnUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(324, 177, -1, -1));

        btnReset.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnReset.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/reset.png"))); // NOI18N
        btnReset.setText("Reset");
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });
        jPanel1.add(btnReset, new org.netbeans.lib.awtextra.AbsoluteConstraints(336, 28, -1, -1));

        txtngaysinh.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("yyyy-MM-dd"))));
        jPanel1.add(txtngaysinh, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 140, 198, 26));

        chkCam.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        chkCam.setText("Cấm");
        jPanel1.add(chkCam, new org.netbeans.lib.awtextra.AbsoluteConstraints(387, 311, -1, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(187, 54, 137));
        jLabel6.setText("Tên tài khoản");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, -1, -1));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(187, 54, 137));
        jLabel12.setText("Vai trò");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 310, -1, -1));

        txttenTK.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jPanel1.add(txttenTK, new org.netbeans.lib.awtextra.AbsoluteConstraints(135, 246, 198, -1));

        cboVaiTro.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cboVaiTro.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel1.add(cboVaiTro, new org.netbeans.lib.awtextra.AbsoluteConstraints(135, 310, 120, -1));

        jLabel13.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(187, 54, 137));
        jLabel13.setText("Mật khẩu");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, -1, -1));

        chkTonTai.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        chkTonTai.setText("Tồn tại");
        jPanel1.add(chkTonTai, new org.netbeans.lib.awtextra.AbsoluteConstraints(303, 311, -1, -1));

        txtpassword.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jPanel1.add(txtpassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(135, 278, 153, -1));

        buttonGroup1.add(rbNam);
        rbNam.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        rbNam.setText("Nam");
        jPanel1.add(rbNam, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 110, -1, -1));

        buttonGroup1.add(rbNu);
        rbNu.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        rbNu.setText("Nữ");
        jPanel1.add(rbNu, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 110, -1, -1));

        jLabel14.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(187, 54, 137));
        jLabel14.setText("Địa chỉ");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 354, -1, -1));

        txtDiaChi.setColumns(20);
        txtDiaChi.setRows(5);
        jScrollPane2.setViewportView(txtDiaChi);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(82, 354, 351, -1));

        jLabel19.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(187, 54, 137));
        jLabel19.setText("Nhập dữ liệu");
        jPanel1.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 458, 85, -1));

        txtFind.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jPanel1.add(txtFind, new org.netbeans.lib.awtextra.AbsoluteConstraints(114, 460, 200, -1));

        btnFind.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnFind.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/find.png"))); // NOI18N
        btnFind.setText("Tìm");
        btnFind.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFindActionPerformed(evt);
            }
        });
        jPanel1.add(btnFind, new org.netbeans.lib.awtextra.AbsoluteConstraints(332, 458, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Ngày bắt đầu:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 510, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Ngày kết thúc:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 560, -1, -1));

        dateNgayKT.setDateFormatString("yyyy-MM-dd");
        dateNgayKT.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jPanel1.add(dateNgayKT, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 510, -1, -1));

        dateNgayBD.setDateFormatString("yyyy-MM-dd");
        dateNgayBD.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jPanel1.add(dateNgayBD, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 560, -1, -1));

        jButton1.setBackground(new java.awt.Color(0, 204, 102));
        jButton1.setText("In thống kê chỉ tiêu");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 530, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, -1, 610));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Danh sách nhân viên", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 14))); // NOI18N
        jPanel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        tblNhanVien.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblNhanVien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblNhanVienMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tblNhanVien);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 988, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 562, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 29, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 80, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private boolean isValidDate(String dateStr) {
        SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
        dateFormat.setLenient(false);
        try {
            dateFormat.parse(dateStr);
            return true;
        } catch (ParseException e) {
            return false;
        }
    }
    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        if (txtmaNV.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn nhân viên muốn cập nhật ở danh sách!");
        } else {
            int maNV = Integer.parseInt(txtmaNV.getText());
            String tentk = txttenTK.getText();
            VaiTro selected = (VaiTro) cboVaiTro.getSelectedItem();
            String password = txtpassword.getText();
            String tennv = txttenNhanVien.getText();
            String ngaysinh = txtngaysinh.getText();
//            SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
//            Date ngaysinh = null;
//            try {
//                ngaysinh = dateFormat.parse(txtngaysinh.getText());
//            } catch (ParseException e) {
//                e.printStackTrace();
//            }

            String gTinh = rbNam.isSelected() ? "Nam" : "Nữ";
            String dc = txtDiaChi.getText();
            String sdt = txtsdt.getText();
            String mail = txtEmail.getText();
            System.out.println(ngaysinh);
            if (tentk.isEmpty() || tennv.isEmpty() || dc.isEmpty() || password.isEmpty() || sdt.isEmpty() || mail.isEmpty() || ngaysinh.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Vui lòng điền đầy đủ thông tin cần thiết.");
                return;
            }
            if (buttonGroup1.getSelection() == null) {
                JOptionPane.showMessageDialog(this, "Vui lòng chọn giới tính");
                return;
            }
            if (selected == null) {
                JOptionPane.showMessageDialog(this, "Vui lòng chọn vai trò.");
                return;
            }

            if (NhanVienDAO.isExistsForUpdate(mail, sdt, tentk, maNV)) {
                JOptionPane.showMessageDialog(this, "Email '" + mail + "\nHoặc SĐT '" + sdt + "\nHoặc tên tài khoản" + tentk + "' đã tồn tại");
                return;
            }
            String hashedPassword;
            NhanVien nv = new NhanVien();
            nv.setIdNhanVien(maNV);
            nv.setTenTaiKhoan(tentk);
            if (password.contains("==:")) {
                hashedPassword = password;
            } else {
                hashedPassword = PasswordHashing.hashPassword(password);
            }
            nv.setMatKhau(hashedPassword);
            nv.setIdVaiTro(selected.getIdVaiTro());
            nv.setTenNhanVien(tennv);
            nv.setNgaySinh(ngaysinh);
            nv.setGioiTinh(gTinh);
            nv.setDiaChi(dc);
            nv.setSoDienThoai(sdt);
            nv.setEmail(mail);
            nv.setTonTai(chkTonTai.isSelected());
            nv.setCam(chkCam.isSelected());
            boolean result = NhanVienDAO.updateById(nv);
            if (result) {
                JOptionPane.showMessageDialog(this, "Cập nhật nhân viên thành công", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
                loadtblNhanVien();
            } else {
                JOptionPane.showMessageDialog(this, "Cập nhật nhân viên thất bại", "Thông báo", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        resetFieldsTTNV();
    }//GEN-LAST:event_btnResetActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        String tentk = txttenTK.getText();
        VaiTro selected = (VaiTro) cboVaiTro.getSelectedItem();
        String password = txtpassword.getText();
        String tennv = txttenNhanVien.getText();
        String ngaysinh = txtngaysinh.getText();
//        SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
//        Date ngaysinh = null;
//        try {
//            ngaysinh = dateFormat.parse(txtngaysinh.getText());
//        } catch (ParseException e) {
//            e.printStackTrace();
//        }

        String gTinh = rbNam.isSelected() ? "Nam" : "Nữ";
        String dc = txtDiaChi.getText();
        String sdt = txtsdt.getText();
        String mail = txtEmail.getText();

        if (tentk.isEmpty() || tennv.isEmpty() || dc.isEmpty() || password.isEmpty() || sdt.isEmpty() || mail.isEmpty() || ngaysinh.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Vui lòng điền đầy đủ thông tin cần thiết.");
            return;
        } else {
            if (buttonGroup1.getSelection() == null) {
                JOptionPane.showMessageDialog(this, "Vui lòng chọn giới tính");
                return;
            }
            if (selected == null) {
                JOptionPane.showMessageDialog(this, "Vui lòng chọn vai trò.");
                return;
            }
            if (ngaysinh == null) {
                JOptionPane.showMessageDialog(this, "Vui lòng nhập ngày sinh hợp lệ.");
                return;
            }
            if (sdt.length() > 10) {
                JOptionPane.showMessageDialog(this, "Định dạng số điện thoại không hợp lệ.");
                return;
            }
        }
        if (NhanVienDAO.isExistsForAdd(mail, sdt, tentk)) {
            JOptionPane.showMessageDialog(this, "Email '" + mail + " \nHoặc SĐT '" + sdt + "\nHoặc tên tài khoản" + tentk + "' đã tồn tại");
        } else {
            NhanVien nv = new NhanVien();
            String hashedPassword = PasswordHashing.hashPassword(password);
            nv.setTenTaiKhoan(tentk);
            nv.setMatKhau(hashedPassword);
            nv.setIdVaiTro(selected.getIdVaiTro());
            nv.setTenNhanVien(tennv);
            nv.setNgaySinh(ngaysinh);
            nv.setGioiTinh(gTinh);
            nv.setDiaChi(dc);
            nv.setSoDienThoai(sdt);
            nv.setEmail(mail);
            nv.setTonTai(chkTonTai.isSelected());
            nv.setCam(chkCam.isSelected());

            boolean result = NhanVienDAO.add(nv);
            if (result) {
                JOptionPane.showMessageDialog(this, "Thêm nhân viên thành công", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
                loadtblNhanVien();
            } else {
                JOptionPane.showMessageDialog(this, "Thêm nhân viên thất bại", "Thông báo", JOptionPane.ERROR_MESSAGE);
            }
        }


    }//GEN-LAST:event_btnAddActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        if (txtmaNV.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn nhân viên muốn xóa ở danh sách!");
        } else {
            int manv = Integer.parseInt(txtmaNV.getText());
            if (NhanVienDAO.isForeignKeyExistsHD(manv) || NhanVienDAO.isForeignKeyExistsHDNK(manv)) {
                JOptionPane.showMessageDialog(this, "Nhân viên đang được sử dụng và không thể xóa!", "Lỗi", JOptionPane.ERROR_MESSAGE);
            } else {
                boolean success = NhanVienDAO.deleteById(manv);
                if (success) {
                    JOptionPane.showMessageDialog(this, "Xóa thành công!", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
                    resetFieldsTTNV();
                    loadtblNhanVien();
                } else {
                    JOptionPane.showMessageDialog(this, "Xóa không thành công!", "Thông báo", JOptionPane.ERROR_MESSAGE);
                }
            }
        }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void tblNhanVienMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblNhanVienMouseClicked
        int row = tblNhanVien.getSelectedRow();
        txtmaNV.setText(tblNhanVien.getValueAt(row, 0) + "");
        txttenTK.setText(tblNhanVien.getValueAt(row, 1) + "");
        txtpassword.setText(tblNhanVien.getValueAt(row, 2) + "");
        Object itemSelectObj = tblNhanVien.getValueAt(row, 3);
        VaiTro itemSelect = (VaiTro) itemSelectObj;
        for (int i = 0; i < cboVaiTro.getItemCount(); i++) {
            String cboValue = cboVaiTro.getItemAt(i) + "";
            if (cboValue.equals(itemSelect.getTenVaiTro())) {
                cboVaiTro.setSelectedIndex(i);
                break;
            }
        }
        txttenNhanVien.setText(tblNhanVien.getValueAt(row, 4) + "");
        txtngaysinh.setText(tblNhanVien.getValueAt(row, 5) + "");
        if (((String) tblNhanVien.getValueAt(row, 6)).contains("Nam")) {
            rbNam.setSelected(true);
        } else {
            rbNu.setSelected(true);
        }
        txtDiaChi.setText(tblNhanVien.getValueAt(row, 7) + "");
        txtsdt.setText(tblNhanVien.getValueAt(row, 8) + "");
        txtEmail.setText(tblNhanVien.getValueAt(row, 9) + "");
        chkTonTai.setSelected((Boolean) tblNhanVien.getValueAt(row, 10));
        chkCam.setSelected((Boolean) tblNhanVien.getValueAt(row, 11));
    }//GEN-LAST:event_tblNhanVienMouseClicked

    private void btnFindActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFindActionPerformed
        String searchValue = txtFind.getText();
        resetFieldsTTNV();
        if (searchValue.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập giá trị tìm kiếm!", "Thông báo", JOptionPane.WARNING_MESSAGE);
            return;
        } else {
            ArrayList<NhanVien> lst = NhanVienDAO.searchNhanVien(searchValue);

            setNhanVienModel(lst);

        }
    }//GEN-LAST:event_btnFindActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnFind;
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btnUpdate;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<Object> cboVaiTro;
    private javax.swing.JCheckBox chkCam;
    private javax.swing.JCheckBox chkTonTai;
    private com.toedter.calendar.JDateChooser dateNgayBD;
    private com.toedter.calendar.JDateChooser dateNgayKT;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JRadioButton rbNam;
    private javax.swing.JRadioButton rbNu;
    private javax.swing.JTable tblNhanVien;
    private javax.swing.JTextArea txtDiaChi;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtFind;
    private javax.swing.JTextField txtmaNV;
    private javax.swing.JFormattedTextField txtngaysinh;
    private javax.swing.JPasswordField txtpassword;
    private javax.swing.JTextField txtsdt;
    private javax.swing.JTextField txttenNhanVien;
    private javax.swing.JTextField txttenTK;
    // End of variables declaration//GEN-END:variables
}
